# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1us/1us -mfcu +acc  C:/Users/stc/OneDrive/Documents/githubActions_Repo/GithubActions/PyUvm_test/tinyalu.sv
vsim  -onfinish exit -pli C:/Users/stc/miniconda3/Lib/site-packages/cocotb/libs/cocotbvpi_modelsim.dll   sim_build/work.tinyalu
onbreak resume
run -all
quit
