name: Black Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Black
        run: |
          pip install black==23.9.1

      - name: Run Black
        run: black --check .
      # - uses: psf/black@stable
