name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: install flake8
        run: pip install flake8
        
      - name: flake8 Lint
        uses: flake8 --ignore=E203 --max-line-length=88 .
        

